### ISSUE TITLE
It seems not to connect

### ISSUE THREAD

**Issue by svenpetersen1965** [ttn-zh/gateway-remote-config#137]
I have a raspi + ic880a (SPI) gateway (4 of them) , running a rasbian lite (jessie). I have also created a json for each of them and created them in the repository. I have created an interface board, that actually only contains the connectors for raspberry pi and the iC880a. It is derived from the ch2i-board (I have removed the powersupply and connector and the RFM95, also connected the gps serial to the ic880a and that's it.

I have followed the instructions, which I have found in the repository. I think, the power supply is ok (I don't see any low power symbol in the raspberry pi monitor top/right).

I have used the remote configuration option, when installing the repository.

The gateways (all four of them) are registered at console.thethingsnetwork.org with their EUIs

To check, if there is anything working, I have used this command:
sudo tail -f /var/log/syslog

This is, what I get:
Apr 10 14:20:34 lacon-lora-gtwy-004 systemd[1]: Starting The Things Network Gateway...
Apr 10 14:20:34 lacon-lora-gtwy-004 systemd[1]: Started The Things Network Gateway.
Apr 10 14:20:35 lacon-lora-gtwy-004 ttn-gateway[19384]: /opt/ttn-gateway/gateway-remote-config /opt/ttn-gateway/bin
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: Already up-to-date.
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: HEAD ist jetzt bei 7c4d14a Create Gateway_Positions.kml
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: /opt/ttn-gateway/bin
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: [TTN Gateway]: Use Gateway EUI B827EBFFFE404115 based on eth0
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: ln: die symbolische Verknüpfung „/opt/ttn-gateway/bin/local_conf.json“ konnte nicht angelegt werden: Die Datei existiert bereits
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: *** Poly Packet Forwarder for Lora Gateway ***
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: Version: 2.1.0
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: *** Lora concentrator HAL library version info ***
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: Version: 3.1.0; Options: native;
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: ***
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Little endian host
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: found global configuration file global_conf.json, parsing it
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: global_conf.json does contain a JSON object named SX1301_conf, parsing SX1301 parameters
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: lorawan_public 1, clksrc 1
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Configuring TX LUT with 16 indexes
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: radio 0 enabled (type SX1257), center frequency 867500000, RSSI offset -166.000000, tx enabled 1
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: radio 1 enabled (type SX1257), center frequency 868500000, RSSI offset -166.000000, tx enabled 0
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Lora multi-SF channel 0>  radio 1, IF -400000 Hz, 125 kHz bw, SF 7 to 12
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Lora multi-SF channel 1>  radio 1, IF -200000 Hz, 125 kHz bw, SF 7 to 12
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Lora multi-SF channel 2>  radio 1, IF 0 Hz, 125 kHz bw, SF 7 to 12
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Lora multi-SF channel 3>  radio 0, IF -400000 Hz, 125 kHz bw, SF 7 to 12
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Lora multi-SF channel 4>  radio 0, IF -200000 Hz, 125 kHz bw, SF 7 to 12
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Lora multi-SF channel 5>  radio 0, IF 0 Hz, 125 kHz bw, SF 7 to 12
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Lora multi-SF channel 6>  radio 0, IF 200000 Hz, 125 kHz bw, SF 7 to 12
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Lora multi-SF channel 7>  radio 0, IF 400000 Hz, 125 kHz bw, SF 7 to 12
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Lora std channel> radio 1, IF -200000 Hz, 250000 Hz bw, SF 7
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: FSK channel> radio 1, IF 300000 Hz, 125000 Hz bw, 50000 bps datarate
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: global_conf.json does contain a JSON object named gateway_conf, parsing gateway parameters
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: gateway MAC address is configured to AA555A0000000000
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Found 2 servers in array.
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Server 0 configured to "127.0.0.1", with port up "1680" and port down "1681"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Server 1 configured to "iot.semtech.com", with port up "1680" and port down "1680"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Found 5 system calls in array.
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: System command 0: "df -m"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: System command 1: "free -h"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: System command 2: "uptime"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: System command 3: "who -a"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: System command 4: "uname -a"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: monitor hostname or IP address is configured to "127.0.0.1"
Apr 10 14:20:36 lacon-lora-gtwy-004 systemd[1]: ttn-gateway.service: main process exited, code=exited, status=1/FAILURE
Apr 10 14:20:36 lacon-lora-gtwy-004 systemd[1]: Unit ttn-gateway.service entered failed state.
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: monitor port is configured to "2008"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: ghost hostname or IP address is configured to "127.0.0.1"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: ghost port is configured to "1918"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: downstream keep-alive interval is configured to 10 seconds
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: statistics display interval is configured to 30 seconds
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: upstream PUSH_DATA time-out is configured to 100 ms
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: packets received with a valid CRC will be forwarded
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: packets received with a CRC error will NOT be forwarded
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: packets received with no CRC will NOT be forwarded
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: GPS serial port path is configured to "/dev/ttyAMA0"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: SSH path is configured to "/usr/bin/ssh"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: SSH port is configured to 22
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: HTTP port is configured to 80
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: NGROK path is configured to "/usr/bin/ngrok"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Reference latitude is configured to 10.000000 deg
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Reference longitude is configured to 20.000000 deg
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Reference altitude is configured to -1 meters
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: GPS is enabled
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Using fake GPS coordinates instead of real.
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Upstream data is enabled
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Downstream data is enabled
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Ghoststream data is disabled
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Radiostream data is enabled
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Statusstream data is enabled
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Beacon is disabled
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Monitor is disabled
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Platform configured to "IMST + Rpi"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Contact email configured to "operator@gateway.tst"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Description configured to "Update me"
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Successfully contacted server 127.0.0.1
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: Successfully contacted server iot.semtech.com
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: INFO: [main] Starting the concentrator
Apr 10 14:20:36 lacon-lora-gtwy-004 ttn-gateway[19384]: ERROR: [main] failed to start the concentrator

Is it running, is there a problem with it?

Reagards
Sven

**Comment by gonzalocasas** [comment]
There seems to be a few problems.

The message saying "failed to start" sounds like you have the wrong pin
number for reset. This is especially likely since you mention the ch2i
board which uses yet a different pin for this.

Then, I don't see the ttn servers in the initialization, which almost for
sure means something went wrong with your remote config and it's not being
taken into account.

**Comment by gonzalocasas** [comment]
Hi again @svenpetersen1965! Regarding the second issue I mentioned, I think you haven't really created a pull request to add your configuration to the remote repository. I see you forked it, but I can't find any commits or pull requests from you.

**Comment by svenpetersen1965** [comment]
Thank you, Gonzalo, great hints. I have rewired the SX_Reset on my board and now, things look much different. I have also made a pull request and now I can see my json in the list.  The LEDs on the iC880a also look different (now only the rightmost green is on - the antenna jack are "up and backwards"). I have registered my gateways on TTN yesterday and I only get a "not connected". 

I am not sure, if the firewall configuration might be the problem (I cannot influence it, here).

What I get now looks like this:
May 30 12:30:57 lacon-lora-gtwy-004 ttn-gateway[464]: ### [UPSTREAM] ###
May 30 12:30:57 lacon-lora-gtwy-004 ttn-gateway[464]: # RF packets received by concentrator: 0
May 30 12:30:57 lacon-lora-gtwy-004 ttn-gateway[464]: # CRC_OK: 0.00%, CRC_FAIL: 0.00%, NO_CRC: 0.00%
May 30 12:30:57 lacon-lora-gtwy-004 ttn-gateway[464]: # RF packets forwarded: 0 (0 bytes)
May 30 12:30:57 lacon-lora-gtwy-004 ttn-gateway[464]: # PUSH_DATA datagrams sent: 1 (254 bytes)
May 30 12:30:57 lacon-lora-gtwy-004 ttn-gateway[464]: # PUSH_DATA acknowledged: 0.00%
May 30 12:30:57 lacon-lora-gtwy-004 ttn-gateway[464]: ### [DOWNSTREAM] ###
May 30 12:30:57 lacon-lora-gtwy-004 ttn-gateway[464]: # PULL_DATA sent: 3 (0.00% acknowledged)
May 30 12:30:57 lacon-lora-gtwy-004 ttn-gateway[464]: # PULL_RESP(onse) datagrams received: 0 (0 bytes)
May 30 12:34:09 lacon-lora-gtwy-004 rsyslogd-2007: action 'action 17' suspended, next retry is Tue May 30 12:35:39 2017 [try http://www.rsyslog.com/e/2007 ]
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # RF packets sent to concentrator: 0 (0 bytes)
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # TX errors: 0
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: ### [GPS] ###
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # Invalid gps time reference (age: 1496140257 sec)
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # Manual GPS coordinates: latitude 48.22719, longitude 11.48256, altitude 491 m
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: ##### END #####
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: ##### 2017-05-30 10:31:27 GMT #####
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: ### [UPSTREAM] ###
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # RF packets received by concentrator: 0
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # CRC_OK: 0.00%, CRC_FAIL: 0.00%, NO_CRC: 0.00%
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # RF packets forwarded: 0 (0 bytes)
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # PUSH_DATA datagrams sent: 1 (254 bytes)
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # PUSH_DATA acknowledged: 0.00%
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: ### [DOWNSTREAM] ###
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # PULL_DATA sent: 3 (0.00% acknowledged)
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # PULL_RESP(onse) datagrams received: 0 (0 bytes)
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # RF packets sent to concentrator: 0 (0 bytes)
May 30 12:34:27 lacon-lora-gtwy-004 ttn-gateway[464]: # TX errors: 0

I just see this "action 17 suspended", which I don't know, what to think about it and olso the "PUSH_DATA datagrams sent: 1 (254 bytes)" and "PUSH_DATA acknowledged: 0.00%". Could it be the firewall?

Regards,
Sven

**Comment by gonzalocasas** [comment]
Hi Sven! Definitely looking much better! The firewall could be a problem
indeed. Do you have a way to test without it just to verify? Maybe setting
up a hotspot with your mobile? In any case, could you paste a longer chunk
of the logfile, especially the part where it initializes?

**Comment by svenpetersen1965** [comment]
Hi Gonzalo, great news: Now I get a connect. I just set up my mobile as a hotspot, so I know, it is matter of the firewall. Thank you so much, you have made my day! Great support.

**Comment by gonzalocasas** [comment]
@svenpetersen1965: glad to hear it works! cool!
