### ISSUE TITLE
How to register my EUI on github

### ISSUE THREAD

**Issue by HyucksoonIM** [ttn-zh/gateway-remote-config#1483]
Dear master,

1. I'd like to know how i can register my EUI on github since I'm not familiar with github.
I've got my EUI code from RPI based on Linux.
and i registered my gateway on THETHINGNETWORK and now its under disconnected.
Also as far as i know, I should register the EUI code on gateway-remote-config.
Could you let me know the way to register?

2. About Installing the TTN packet forwarder on a RPI with an IMST ic880a board,
I've tried to do while following the manual. 
1) I did download the Raspberry Pi + IMST build on the RPI3.
2) i couldn't configure the packet forwarder
' $ <packet-forwarder-binary> configure ' is not working.

**Comment by gonzalocasas** [comment]
There's no `configure` step required in the installer. Please follow the instructions here: https://github.com/ttn-zh/ic880a-gateway/wiki

I am going to close this issue because it's actionable, but feel free to keep commenting.

**Comment by HyucksoonIM** [comment]
Thank you for replying it.

and i have one more question.
 Q) Can i use Raspbian instead of Lite version?
I hope i would register the gateway and use your sever as soon as possible

Thank you. Regards

2020년 1월 12일 (일) 오후 5:10, Gonzalo Casas <notifications@github.com>님이 작성:

**Comment by gonzalocasas** [comment]
Yes, you can use raspbian.

**Comment by HyucksoonIM** [comment]
Sorry, one more question.
[image: image.png]
on the instructions, Is it necessary to do this procedure?


2020년 1월 13일 (월) 오전 9:14, Gonzalo Casas <notifications@github.com>님이 작성:

**Comment by gonzalocasas** [comment]
The image you attached on your email gets lost on github, so, please upload it here instead, or described the part of the procedure with text. ;)

**Comment by HyucksoonIM** [comment]
Okay, in the instructions,
============================================================================================
! Beware this allows a connected console with the ttn user to issue any
commands on your system.
without any password control, This step is completely optional and remains
your decision.

 - Logout and login as ttn and remove the default pi user
 - Configure the wifi credentials (check here for additional details)
============================================================================================
 Do I have to follow this one also?
 if not, what section can i start with?

Thank you.

2020년 1월 13일 (월) 오후 4:38, Gonzalo Casas <notifications@github.com>님이 작성:

**Comment by HyucksoonIM** [comment]
I've done according to the instructions you attached.
but the gateway i registered is under not connected.
EUI: B827EBFFFEE3F703

How can i get the gateway connected?
Don't I need to upload something on the github?

2020년 1월 14일 (화) 오전 8:18, 임혁순 <lhs930920@gmail.com>님이 작성:

**Comment by gonzalocasas** [comment]
It is most likely something not working on your setup, check `syslog` and the status of the packet forwarder service to verify if it's actually running in your RPi.

**Comment by HyucksoonIM** [comment]
According to the instructions,
============================================================================================
! Beware this allows a connected console with the ttn user to issue any
commands on your system.
without any password control, This step is completely optional and remains
your decision.

 - Logout and login as ttn and remove the default pi user
 - Configure the wifi credentials (check here for additional details)
============================================================================================
 Do I have to follow this one also?


and what is the ttn-zh/gateway-remote-config for?
don't i need to register something here?


2020년 1월 14일 (화) 오후 12:40, Gonzalo Casas <notifications@github.com>님이 작성:

**Comment by gonzalocasas** [comment]
>  Do I have to follow this one also?

It clearly says that it is up to you. You don't *have* to do follow it, it's optional.

> what is the ttn-zh/gateway-remote-config for

It is only to have a way to modify the config of the gateway without having to SSH into it, because the gateway will automatically pull from this from this repository when it restarts (if you selected `YES` to the option of remote config).

> don't i need to register something here?

Here, the only needed steps is to create a file with an EUI that matches your gateway.

But if you don't need remote config, then just use local and it will be easier, in the local mode, you don't need to upload anything here.
