### ISSUE TITLE
how to change my server adress to my local host

### ISSUE THREAD

**Issue by manivalaguru** [ttn-zh/gateway-remote-config#1592]
hello i am using ic880a with rasperry pi with ttn now i have created my own udp bridge app server and network server for that i want to change default server_address to router_eu_thethings.network to 127.0.0.1  i have tired changing in local_conf.json under bin and also (mymac).json in gateway-remote-config but none of that worked can you tell where should i change to make it permanent
thanks and regards
manikandan v

**Comment by gonzalocasas** [comment]
re-install and choose No to the remote config option and then you can manage your local_conf.json locally without it being overwritten by the remote data.
