### ISSUE TITLE
B827EBFFFEB78797.json

### ISSUE THREAD

**Issue by glosair** [ttn-zh/gateway-remote-config#1649]
{
  "gateway_conf": {
    "gateway_ID": "B827EBFFFEB78797",
    "servers": [
      {
        "server_address": "router.eu.thethings.network",
        "serv_port_up": 1700,
        "serv_port_down": 1700,
        "serv_enabled": true
      }
    ],
    "ref_latitude": 51.850398,
    "ref_longitude": -2.245056,
    "ref_altitude": 40,
    "contact_email": "info@glosair.co.uk",
    "description": "TTN Gloucester glosair.co.uk"
  }
}

**Comment by gonzalocasas** [comment]
Please open a pull request with this, not an issue.
