### ISSUE TITLE
Cant create pull request

### ISSUE THREAD

**Issue by yldzmuhammed** [ttn-zh/gateway-remote-config#297]
Hello.
I have RAK831 and Raspberr Pi 3.
I'm trying to make the RAK831 card work.
I've done all the things that the manufacturer has published. Except for the "pull-request" part.
As mentioned in the documentation, I create a file with a json extension with the EUI ID for my GATEWAY (eg B827EBFFFE6707A2.json).
I fill it in the way it says on the document. But I can not load this project with pull-request.
How can I do it?

**Comment by gonzalocasas** [comment]
You already created it yesterday, and I already merged it about an hour ago.
