### ISSUE TITLE
 wrong server_adress in my uploaded json file 

### ISSUE THREAD

**Issue by Riesro** [ttn-zh/gateway-remote-config#666]
Hi,
I think I have the wrong server_adress in my uploaded json file "b827ebfffe8a799d.json"
The correct one I thin is:
"server_address": "router.eu.thethings.network",

new file:
[b827ebfffe8a799d.zip](https://github.com/ttn-zh/gateway-remote-config/files/1866585/b827ebfffe8a799d.zip)

Coud you change the file?
Thanks a lot

Robert (riesro@gmx,de)

**Comment by gonzalocasas** [comment]
I see you just did, but then closed the PR again. Do you want to open a new one with the correct settings? Also, please notice that the EUI should be in upper case inside the file as well as on the name.

**Comment by Riesro** [comment]
yes i will do
